# Generated by Django 5.2.1 on 2025-05-13 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 12, 5, 37, 222506)),
        ),
    ]
