# Generated by Django 5.2.1 on 2025-05-13 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0003_pointsofdelivery_user_wholesalers_alter_faq_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 16, 25, 33, 99943, tzinfo=datetime.timezone.utc)),
        ),
    ]
