# Generated by Django 5.2.1 on 2025-05-13 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0010_alter_faq_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 18, 40, 43, 308470, tzinfo=datetime.timezone.utc)),
        ),
    ]
