# Generated by Django 5.2.1 on 2025-05-13 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0011_alter_faq_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 18, 54, 28, 826019, tzinfo=datetime.timezone.utc)),
        ),
    ]
