# Generated by Django 5.2.1 on 2025-05-13 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0012_remove_user_type_alter_faq_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
