# Generated by Django 5.2.1 on 2025-05-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0013_alter_faq_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
    ]
