# Generated by Django 5.2.1 on 2025-05-14 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0018_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtfurniture',
            name='bought_by',
        ),
        migrations.AddField(
            model_name='boughtfurniture',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
