# Generated by Django 5.2.1 on 2025-05-14 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0019_remove_boughtfurniture_bought_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtfurniture',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
