# Generated by Django 5.2.1 on 2025-05-14 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0020_alter_boughtfurniture_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
