# Generated by Django 5.2.1 on 2025-05-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0021_contacts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalers',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
