# Generated by Django 5.2.1 on 2025-05-15 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0022_wholesalers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtfurniture',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture_factory.furniture'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
