# Generated by Django 5.1.11 on 2025-09-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0024_comment_date_comment_rating_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+375291435499', max_length=20),
        ),
    ]
