# Generated by Django 5.1.12 on 2025-09-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0025_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cert',
            field=models.TextField(default='rnd_name'),
        ),
    ]
