# Generated by Django 5.1.12 on 2025-09-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0026_about_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='logo',
            field=models.FileField(upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
