# Generated by Django 5.1.12 on 2025-09-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0027_alter_about_logo_alter_about_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='shorthand',
            field=models.CharField(default='', max_length=255),
        ),
    ]
