# Generated by Django 5.1.12 on 2025-09-16 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0031_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='furn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='furniture_factory.furniture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='furnitures',
            field=models.ManyToManyField(to='furniture_factory.cartitem'),
        ),
    ]
