# Generated by Django 5.1.12 on 2025-09-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0032_cartitem_furn_alter_cart_furnitures'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='count',
            field=models.IntegerField(auto_created=1, default=1),
            preserve_default=False,
        ),
    ]
