# Generated by Django 5.2.1 on 2025-09-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0033_cartitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.CharField(default='general', max_length=255),
            preserve_default=False,
        ),
    ]
