# Generated by Django 5.1.13 on 2025-11-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0034_comment_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='rndemail@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.TextField(default='+375382283711'),
        ),
    ]
