# Generated by Django 5.1.13 on 2025-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_factory', '0035_contacts_email_contacts_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='user',
        ),
        migrations.AddField(
            model_name='contacts',
            name='username',
            field=models.TextField(default='labwc'),
        ),
    ]
